### PR TITLE
Adding Docker files

### PR DESCRIPTION
**Pull request by XMaarten**
I created a docker-compose with Dockerfile to easily run this inside a Docker container.

```
git clone https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA.git /etc/p2000
docker-compose up --force-recreate --build -d p2000
```

### CODE REVIEW

**Comment by Dinges28** [comment]
Nice!!
I already tried it. But got stuck when adding the changed drivers... 

Thanx for the effort. Wil test it (probably this weekend)

**Comment by XMaarten** [comment]
One of the things you need to do is make sure that the drivers aren't being loaded on the host itself:
```
# cat /etc/modprobe.d/blacklist-rtl.conf
blacklist rtl2832
blacklist r820t
blacklist rtl2830
blacklist dvb_usb_rtl28xxu
```

**Comment by Dinges28** [comment]
> One of the things you need to do is make sure that the drivers aren't being loaded on the host itself:
> 
> ```
> # cat /etc/modprobe.d/blacklist-rtl.conf
> blacklist rtl2832
> blacklist r820t
> blacklist rtl2830
> blacklist dvb_usb_rtl28xxu
> ```

En you do that by cloning git://git.osmocom.org/rtl-sdr.git
and executing line 9-17?

**Comment by XMaarten** [comment]
The blacklist is for the docker host, to prevent it from using the build in drivers. The Dockerfile installs rtl-sdr on the Docker container similar as the readme of RTL-SDR_P2000Receiver indicates. So it will be the docker container that loads the drivers and communicates directly to the USB device.

**Comment by Dinges28** [comment]
So it is an extra step to take on de Docker machine?

**Comment by XMaarten** [comment]
If you mean the blacklist, yes. The container can't use the USB device if the host is already using it.

**Comment by Dinges28** [comment]
its getting more cloudy, with every comment...

I had a problem making this project containerised because of the drivers that have to be disconnected.
you come with the blacklist part... and i ask the question if that has to be done to the host besides starting/creating a container.. 8-)

Is disconnecting the drivers done inside the container? Or do we have to put that in a readme to do this as an extra step on the host?

Also, we need to change the p2000.py to read and put the config (and in de compose, mount a volume), database files and logfiles on a different folder/file location, otherwise it will be lost after recreating the container.

**Comment by XMaarten** [comment]
Two comments it says "The blacklist is for the docker host, to prevent it from using the build in drivers. " .  I don't understand your question and confusion. 

I agree about splitting the code from the config. I put the whole project in a volume now to prevent things from being lost, but it is indeed best to split both up and have the code in the container and the rest of the files in a volume.

**Comment by Dinges28** [comment]
Ok, but I have it now running on the host itself, without the blacklist of the drivers.. 
(i'm trying to understand WHY it is necessary to do this extra step (which we should document in de guide for using a container) and why it is not needed when using it on the host itself)
I'm not trying to make it more difficult or nagging about this issue, I'm trying to gain some knowledge on this point

**Comment by XMaarten** [comment]
This is because the host and container can't be using the device at the same time. I experienced this issue and found that blacklisting the drivers on the host solved it.

See https://github.com/sdr-enthusiasts/docker-piaware#prerequisites for more information

**Comment by Dinges28** [comment]
Now i get it.. .sorry for the misunderstanding.

**Comment by cyberjunky** [comment]
Thanks! Picking up development after a long pause ;-)

**Pull request merged**
