### PR TITLE
Update p2000.py

### PR DESCRIPTION
**Pull request by Dinges28**
394-402; Adding an option to log all posted and ignored p2000 messages, usecase: history log
510-602; Created a loop to check all different sensors discovered in the config.ini
782-798; Discovered that some regions post messages with postal codes, only the digits, not the letters
959; send all found capcodes to msg, to provide a possibility to search on capcodes

### CODE REVIEW

**Comment by cyberjunky** [comment]
Thanks! 
Will add it, but maybe change the logging of messages to use the Logger and Filerotate code, so we have them rotated and named automatically.

If i understand the changes correctly at first glance we do a selection of message first using the match and ignore .txt files first and later on match them again using the per sensor settings?

Do you think about removing the file match/discard txt file later, and just rely on per sensor settings?
Or should we just have parameters per sensor to define the match_ and ignore_ files ti use for that sensor (this was my initial idea, but uses more code)

So you can have for example:
sensor_p2000_match_capcodes.txt
sensor_dordrecht_match_capcodes.txt etc.

What do you think?

**Comment by Dinges28** [comment]
So you want to do the log file based on the other log file you already implemented in the last version. That sounds nice. Did not had the vision on how to do that. 
I found myself sometimes want to search back. If I had missed or successful found a p2000 message

**Comment by cyberjunky** [comment]
Yes logging p2000 messages seperate;y is a nice feature, will look into it.
We need to change something like add filename parameter to those routines.

**Comment by Dinges28** [comment]
The filtering. 
My opinion. 
If I DONT want to see messages. I do not want that for all sensors. 

If I do want a sensor that just receives (for instance; grip messages) based on keyword or capcode. Than it is only for THAT sensor. The other sensors will receive all messages.

**Comment by Dinges28** [comment]
The match_txt removal. I think we can do that. If it proven it is not necessary for later

**Comment by cyberjunky** [comment]
BTW: The current version of the code is very stable, while running from /etc/rc.local. Before I had it to crash/quit for unknown reason (that's why I added better logging) but stil haven't found the cause. Anyway it runs for weeks without issues here.

**Comment by Dinges28** [comment]
Oooh. You mean separated files per sensor. That can also be a good option. 
Although. It might be simpeler (for other users) to put everything in 1 config file??

**Comment by cyberjunky** [comment]
Good point to gave global ignore but per sensor match and radius settings.

**Comment by Dinges28** [comment]
> Yes logging p2000 messages seperate;y is a nice feature, will look into it.
> 
> We need to change something like add filename parameter to those routines.

That can be simply done in config.ini file name with automatic added date after the name

**Comment by Dinges28** [comment]
> BTW: The current version of the code is very stable, while running from /etc/rc.local. Before I had it to crash/quit for unknown reason (that's why I added better logging) but stil haven't found the cause. Anyway it runs for weeks without issues here.

I have the same experience, long uptime. And from HASS. I send out a notification it the sensor is not updated for more than 30 minutes. 

And with that speaking. 
Can we include posting every time something is received an "ok" to a different sensor in HASS, sort of a heartbeat sensor?
Or can we monitor that on a different way from HASS??

**Pull request merged**
